export const frontendPermissions = [
  {
    name: 'nav_dashboard',
    resource: 'Dashboard',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Dashboard main page in quick access section',
  },
  {
    name: 'nav_dashboard_analytic',
    resource: 'Dashboard Analytic',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Dashboard analytic page in quick access section',
  },
  {
    name: 'nav_dashboard_quick_access',
    resource: 'Dashboard Quick Access',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Dashboard quick access page in dashboards section',
  },
  {
    name: 'nav_user_overview',
    resource: 'User Overview',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'User overview page in dashboards quick access section',
  },
  {
    name: 'nav_platform_user_management_overview',
    resource: 'Platform User Management Overview',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'User management overview page under platform navigation',
  },
  {
    name: 'nav_platform_user_management_role_management',
    resource: 'Platform User Management Role Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Role management page under platform user management navigation',
  },
  {
    name: 'nav_platform',
    resource: 'Platform',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Platform main navigation entry',
  },
  {
    name: 'nav_platform_user_management',
    resource: 'Platform User Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'User management section in platform navigation',
  },
  {
    name: 'nav_platform_crew_management',
    resource: 'Platform Crew Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Crew management section in platform navigation',
  },
  {
    name: 'nav_platform_vessel_management',
    resource: 'Platform Vessel Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Vessel management section in platform navigation',
  },
  {
    name: 'nav_platform_telephony',
    resource: 'Platform Telephony',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Telephony section in platform navigation',
  },
  {
    name: 'nav_platform_crew_management_crew_login',
    resource: 'Platform Crew Login',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Crew login page under crew management navigation',
  },
  {
    name: 'nav_platform_vessel_management_vessel_overview',
    resource: 'Platform Vessel Overview',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Vessel overview page under vessel management navigation',
  },
  {
    name: 'nav_platform_vessel_management_group_overview',
    resource: 'Platform Group Overview',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Group overview page under vessel management navigation',
  },
  {
    name: 'nav_platform_mikrotik_management',
    resource: 'Platform Mikrotik Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Mikrotik management section in platform navigation',
  },
  {
    name: 'nav_platform_mikrotik_management_mikrotik_status',
    resource: 'Platform Mikrotik Status',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Mikrotik status page under Mikrotik management navigation',
  },
  {
    name: 'nav_platform_mikrotik_management_add_mikrotik_vessel',
    resource: 'Add Mikrotik Vessel',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Add Mikrotik vessel page under Mikrotik management navigation',
  },
  {
    name: 'nav_platform_mikrotik_management_hotspot',
    resource: 'Platform Hotspot',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Hotspot page under Mikrotik management navigation',
  },
  {
    name: 'nav_platform_mikrotik_management_hotspot_pin_generator',
    resource: 'Hotspot PIN Generator',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Hotspot PIN generator page under Mikrotik management navigation',
  },
  {
    name: 'nav_platform_mikrotik_management_firewall',
    resource: 'Platform Firewall',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Firewall page under Mikrotik management navigation',
  },
  {
    name: 'nav_platform_access_control',
    resource: 'Platform Access Control',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Access control section in platform navigation',
  },
  {
    name: 'nav_platform_access_control_group_permissions',
    resource: 'Group Permissions',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Group permissions page under access control navigation',
  },
  {
    name: 'nav_platform_access_control_manage_organizations',
    resource: 'Manage Organizations',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Manage organizations page under access control navigation',
  },
  {
    name: 'nav_platform_access_control_permission_management',
    resource: 'Permission Management',
    action: 'view',
    scope: 'organization',
    category: 'navigation',
    section: 'organization',
    description: 'Permission management page under access control navigation',
  },
]