
services:
  # Bun Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=postgresql://root:example@postgres:5432/space_vision
    depends_on:
      - postgres
    networks:
      - dbs

  # Database Admin Interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8090:8080
    networks:
      - dbs

  # PostgreSQL Database
  postgres:
    image: cgr.dev/chainguard/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: space_vision
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dbs

  chat2db:
    image: chat2db/chat2db:latest
    container_name: chat2db-latest
    volumes:
      - ~/.chat2db-docker:/root/.chat2db
    ports:
      - "10824:10824"
    
networks:
  dbs:
    driver: bridge

volumes:
  postgres_data: